apiVersion: v1
kind: Service
metadata:
  name:  test-rtp-service
  namespace: test
spec:
  type: NodePort
  selector:
    app: test-rtp
  ports:
  - nodePort: 30082
    port: 8000
    targetPort: 8000